### ISSUE TITLE
Traceback at startup

### ISSUE THREAD

**Issue by karlb** [bowd/crucible#2]
```
> crucible 
Traceback (most recent call last):
  File "/Users/karl/.local/bin/crucible", line 5, in <module>
    from crucible.app import crucible
  File "/Users/karl/.local/pipx/venvs/forge-crucible/lib/python3.11/site-packages/crucible/app.py", line 2, in <module>
    from crucible.screens.suite import SuiteScreen
  File "/Users/karl/.local/pipx/venvs/forge-crucible/lib/python3.11/site-packages/crucible/screens/suite.py", line 11, in <module>
    from .test import TestScreen
  File "/Users/karl/.local/pipx/venvs/forge-crucible/lib/python3.11/site-packages/crucible/screens/test.py", line 34
    self.title = f"{node.suite.contract.split(
                 ^
SyntaxError: unterminated string literal (detected at line 34)
```

forge-crucible 0.1.22, installed using Python 3.11.9

**Comment by bowd** [comment]
Ah yeah I need to pin it to python >=3.12 <3

**Comment by bowd** [comment]
Published a new version which I think should require python ^3.12 and I hope pipx handles that.
